
services:
  spring-api-expense-tracker:
    container_name: spring-api-expense-tracker-container
    image: spring-api-expense-tracker
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - expense-tracker-network
    depends_on:
      - postgres
  postgres:
    image: postgres:14.3
    container_name: postgres
    ports:
      - "5432:5432"
    networks:
        - expense-tracker-network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: expense_tracker
    volumes:
      - postgres_data:/var/lib/postgresql/data
networks:
    expense-tracker-network:
volumes:
    postgres_data: